Algoritmo "idade"


Var

   nome1, nome2: caractere
   idade1, idade2: inteiro
   media: real

Inicio

      escreval("Digite o nome e depois a idade da primeira pessoa:")
      leia(nome1)
      leia(idade1)
      escreval("Digite o nome e depois a idade da segunda pessoa:")
      leia(nome2)
      leia(idade2)
      
      media <-  (idade1 + idade2)/2
      
      escreval ("A média da idade de ", nome1, " e de ", nome2, " é de ", media:3:1, " anos.")

Fimalgoritmo